name: Test Maven Build Pipeline

on:
  push:
    branches:
      - main

jobs:
  test-build:
    uses: health-education-england/.github/.github/workflows/build-maven.yml@TIS21-7971-investigate-composite-action-approach-for-unified-workflows
    with:
      dockerfile-path: ${{ inputs.dockerfile-path }}
      project-prefix: ${{ inputs.project-prefix }}
      ecr-repository: 'debug-test'
      java-version: '11'
      use-codeartifact: false
    secrets:
      sonar-token: ${{ secrets.GITHUB_TOKEN }}